version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo "Packaging Lambda code..."
artifacts:
  files:
    - index.py

# random comments not related to buildspec